import DateTime from './date-time.js';
import { fromArray, fromDate, fromFormat, fromISOString, fromTimestamp, now } from './static/create.js';
import { dayOfYear, daysInMonth as _daysInMonth, daysInYear as _daysInYear, getDefaultLocale, getDefaultTimeZone, isLeapYear as _isLeapYear, setDateClamping, setDefaultLocale, setDefaultTimeZone } from './static/utility.js';
import { getDate, getDay, getDayOfYear, getHours, getMilliseconds, getMinutes, getMonth, getQuarter, getSeconds, getTimestamp, getWeek, getWeekDay, getWeekDayInMonth, getWeekOfMonth, getWeekYear, getYear } from './prototype/attributes-get.js';
import { setDate, setDay, setDayOfYear, setHours, setMilliseconds, setMinutes, setMonth, setQuarter, setSeconds, setTimestamp, setWeek, setWeekDay, setWeekDayInMonth, setWeekOfMonth, setWeekYear, setYear } from './prototype/attributes-set.js';
import { add, endOf, startOf, sub } from './prototype/manipulate.js';
import { format, toDateString, toISOString, toString, toTimeString, toUTCString } from './prototype/output.js';
import { dayName, dayPeriod, daysInMonth, daysInYear, diff, era, humanDiff, isAfter, isBefore, isBetween, isDST, isLeapYear, isSame, isSameOrAfter, isSameOrBefore, monthName, timeZoneName, weeksInYear } from './prototype/utility.js';

DateTime.dayOfYear = dayOfYear;
DateTime.daysInMonth = _daysInMonth;
DateTime.daysInYear = _daysInYear;
DateTime.fromArray = fromArray;
DateTime.fromDate = fromDate;
DateTime.fromFormat = fromFormat;
DateTime.fromISOString = fromISOString;
DateTime.fromTimestamp = fromTimestamp;
DateTime.getDefaultLocale = getDefaultLocale;
DateTime.getDefaultTimeZone = getDefaultTimeZone;
DateTime.isLeapYear = _isLeapYear;
DateTime.now = now;
DateTime.setDateClamping = setDateClamping;
DateTime.setDefaultLocale = setDefaultLocale;
DateTime.setDefaultTimeZone = setDefaultTimeZone;

const proto = DateTime.prototype;

proto.add = add;
proto.dayName = dayName;
proto.dayPeriod = dayPeriod;
proto.daysInMonth = daysInMonth;
proto.daysInYear = daysInYear;
proto.diff = diff;
proto.endOf = endOf;
proto.era = era;
proto.format = format;
proto.getDate = getDate;
proto.getDay = getDay;
proto.getDayOfYear = getDayOfYear;
proto.getHours = getHours;
proto.getMilliseconds = getMilliseconds;
proto.getMinutes = getMinutes;
proto.getMonth = getMonth;
proto.getQuarter = getQuarter;
proto.getSeconds = getSeconds;
proto.getTimestamp = getTimestamp;
proto.getWeek = getWeek;
proto.getWeekDay = getWeekDay;
proto.getWeekDayInMonth = getWeekDayInMonth;
proto.getWeekOfMonth = getWeekOfMonth;
proto.getWeekYear = getWeekYear;
proto.getYear = getYear;
proto.humanDiff = humanDiff;
proto.isAfter = isAfter;
proto.isBefore = isBefore;
proto.isBetween = isBetween;
proto.isDST = isDST;
proto.isLeapYear = isLeapYear;
proto.isSame = isSame;
proto.isSameOrAfter = isSameOrAfter;
proto.isSameOrBefore = isSameOrBefore;
proto.monthName = monthName;
proto.setDate = setDate;
proto.setDay = setDay;
proto.setDayOfYear = setDayOfYear;
proto.setHours = setHours;
proto.setMilliseconds = setMilliseconds;
proto.setMinutes = setMinutes;
proto.setMonth = setMonth;
proto.setQuarter = setQuarter;
proto.setSeconds = setSeconds;
proto.setTimestamp = setTimestamp;
proto.setWeek = setWeek;
proto.setWeekDay = setWeekDay;
proto.setWeekDayInMonth = setWeekDayInMonth;
proto.setWeekOfMonth = setWeekOfMonth;
proto.setWeekYear = setWeekYear;
proto.setYear = setYear;
proto.startOf = startOf;
proto.sub = sub;
proto.timeZoneName = timeZoneName;
proto.toDateString = toDateString;
proto.toISOString = toISOString;
proto.toString = toString;
proto.toTimeString = toTimeString;
proto.toUTCString = toUTCString;
proto.weeksInYear = weeksInYear;

export default DateTime;
